import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"
import Login from "../components/login"
import { getSession } from "next-auth/client"

export default function Home({ session }) {
    if (!session) return <Login />
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
    
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)
  
  return {
    props: {
      session
    }
  }
}
